name: Crosspost to Reddit
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
    crosspost:
        runs-on: ubuntu-latest
        steps:
            - name: setup repo
              uses: actions/checkout@v3

            - name: setup go
              uses: actions/setup-go@v3
              with:
                  go-version: ">=1.18.0"

            - name: build it
              run: go build .

            - name: run it
              env:
                  REDDIT_APP_ID: ${{ secrets.REDDIT_APP_ID}}
                  REDDIT_APP_SECRET: ${{ secrets.REDDIT_APP_SECRET}}
                  REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME}}
                  REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD}}
              run: REDDIT_APP_ID="${REDDIT_APP_ID}" REDDIT_APP_SECRET="${REDDIT_APP_SECRET}" REDDIT_USERNAME="${REDDIT_USERNAME}" REDDIT_PASSWORD="${REDDIT_PASSWORD}" ./reddit_bounty_bot
